=== TamezeDev/virtual-tech-seller/docs/xml_xsd/import_products.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- ========
        SIMPLE TYPE
        ============-->

    <xs:simpleType name="PriceType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.01" />
            <xs:maxInclusive value="2000.00" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="StockType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="99" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DiscountType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.01" />
            <xs:maxInclusive value="99.9" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CategoryNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Smartphones" />
            <xs:enumeration value="Videojuegos" />
            <xs:enumeration value="Componentes PC" />
            <xs:enumeration value="Videoconsolas" />
            <xs:enumeration value="Periféricos" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CategoryIdType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="5" />
        </xs:restriction>
    </xs:simpleType>


    <!-- ========
        COMPLEX TYPE
            ========= -->

    <xs:complexType name="CategoryType">
        <xs:sequence>
            <xs:element name="name" type="CategoryNameType" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="idCategory" type="CategoryIdType" use="optional" />
    </xs:complexType>

    <xs:complexType name="NewProductType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="basePrice" type="PriceType" />
            <xs:element name="urlImage" type="xs:string" />
            <xs:element name="available" type="xs:boolean" minOccurs="0" />
            <xs:element name="category" type="CategoryType" />
            <xs:element name="stock" type="StockType" />
            <xs:element name="releaseDate" type="xs:date" />
        </xs:sequence>
        <xs:attribute name="idProduct" type="xs:integer" use="optional" />
    </xs:complexType>

    <xs:complexType name="UsedProductType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="basePrice" type="PriceType" />
            <xs:element name="urlImage" type="xs:string" />
            <xs:element name="available" type="xs:boolean" minOccurs="1" />
            <xs:element name="category" type="CategoryType" />
            <xs:element name="discountPercentage" type="DiscountType" />
            <xs:element name="remark" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="idProduct" type="xs:integer" use="optional" />
    </xs:complexType>

    <!-- =============
        ROOT ELEMENT
        ============= -->
    <xs:element name="products">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="newProduct" type="NewProductType" />
                <xs:element name="usedProduct" type="UsedProductType" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TamezeDev/virtual-tech-seller/docs/xml_xsd/valid_import_products.xml
<?xml version="1.0" encoding="UTF-8"?>

<products
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="import_products.xsd">

    <newProduct>
        <name>KOCH MEDIA GMBH Evercade</name>
        <description>Consola retro</description>
        <basePrice>121.33</basePrice>
        <urlImage>/img/products/ASSET_MP_162770075.jpg</urlImage>
        <category>
            <name>Videoconsolas</name>
        </category>
        <stock>15</stock>
        <releaseDate>2026-01-10</releaseDate>
    </newProduct>
    <newProduct>
        <name>NK-IG33005 NK</name>
        <description>Mando PS4</description>
        <basePrice>15.00</basePrice>
        <urlImage>/img/products/ASSET_MP_164534187.jpg</urlImage>
        <category>
            <name>Videoconsolas</name>
        </category>
        <stock>18</stock>
        <releaseDate>2022-06-10</releaseDate>
    </newProduct>
    <usedProduct>
        <name>Arcade Pokémon Friend</name>
        <description>Consola portátil</description>
        <basePrice>72.90</basePrice>
        <urlImage>/img/products/ASSET_MMS_172899323.jpg</urlImage>
        <available>true</available>
        <category>
            <name>Videoconsolas</name>
        </category>
        <discountPercentage>32</discountPercentage>
        <remark>Producto con desperfectos visibles</remark>
    </usedProduct>
    <usedProduct>
        <name>BLADE Verde</name>
        <description>Accesorios PS5</description>
        <basePrice>20.34</basePrice>
        <urlImage>/img/products/ASSET_MP_173773653.jpg</urlImage>
        <available>true</available>
        <category>
            <name>Videoconsolas</name>
        </category>
        <discountPercentage>50</discountPercentage>
        <remark>Aún conservado en su caja</remark>
    </usedProduct>
    <newProduct>
        <name>Logitech Lift Ergonómico</name>
        <description>Ratón inalámbrico</description>
        <basePrice>35.12</basePrice>
        <urlImage>/img/products/ASSET_MMS_94407401.jpg</urlImage>
        <category>
            <name>Periféricos</name>
        </category>
        <stock>25</stock>
        <releaseDate>2023-06-22</releaseDate>
    </newProduct>
    <newProduct>
        <name>Google Pixel 9a</name>
        <description>128 GB, 8 GB RAM, 6.3" Actúa pOLED, Google Tensor G4, 5100 mAh</description>
        <basePrice>322.68</basePrice>
        <urlImage>/img/products/ASSET_MMS_150858184.jpg</urlImage>
        <category>
            <name>Smartphones</name>
        </category>
        <stock>15</stock>
        <releaseDate>2024-07-14</releaseDate>
    </newProduct>
    <newProduct>
        <name>OPPO Reno14FS</name>
        <description>12GB, 12GB RAM, 6.57" 2.5D AMOLED, Snapdragon® 6 Gen 1</description>
        <basePrice>280.18</basePrice>
        <urlImage>/img/products/ASSET_MMS_160757795.jpg</urlImage>
        <category>
            <name>Smartphones</name>
        </category>
        <stock>12</stock>
        <releaseDate>2025-03-14</releaseDate>
    </newProduct>
    <newProduct>
        <name>Sveon STV60</name>
        <description>Capturadora de vídeo</description>
        <basePrice>8.15</basePrice>
        <urlImage>/img/products/ASSET_MMS_93093830.jpg</urlImage>
        <category>
            <name>Componentes PC</name>
        </category>
        <stock>8</stock>
        <releaseDate>2026-03-14</releaseDate>
    </newProduct>
    <newProduct>
        <name>La Lego Ninjago Película</name>
        <description>Videojuego Nintendo Switch</description>
        <basePrice>16.55</basePrice>
        <urlImage>/img/products/pixelboxx-mss-78944035.jpg</urlImage>
        <category>
            <name>Videojuegos</name>
        </category>
        <stock>10</stock>
        <releaseDate>2026-03-14</releaseDate>
    </newProduct>
</products>
